# Prometheus configuration for Arena MVP Platform
# Version: 2.45.0
# Purpose: Core metrics collection and monitoring configuration

global:
  # Standard collection intervals aligned with Grafana datasource timeInterval
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s
  
  # Environment labels for metrics identification
  external_labels:
    environment: ${ENV}
    region: ${AWS_REGION}

# Scrape configurations for Arena services
scrape_configs:
  # API Service metrics collection
  - job_name: 'arena-api'
    metrics_path: '/metrics'
    scheme: 'http'
    static_configs:
      - targets: ['api:8000']
        labels:
          service: 'api'
          environment: ${ENV}
    # Filter to collect only relevant metrics
    metric_relabel_configs:
      - source_labels: ['__name__']
        regex: '(http_request_duration_seconds|http_requests_total|process_.*)'
        action: 'keep'

  # Celery Worker metrics collection
  - job_name: 'arena-celery'
    metrics_path: '/metrics'
    scheme: 'http'
    static_configs:
      - targets: ['celery:8001']
        labels:
          service: 'worker'
          environment: ${ENV}
    # Filter worker-specific metrics
    metric_relabel_configs:
      - source_labels: ['__name__']
        regex: '(ai_processing_duration_seconds|task_.*|process_.*)'
        action: 'keep'

# AlertManager integration
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
      scheme: 'http'
      timeout: 5s
      api_version: 'v2'

# Alert rules configuration
rule_files:
  - /etc/prometheus/rules/*.yml

# Storage configuration
storage:
  tsdb:
    path: /prometheus
    retention:
      time: 15d
      size: 50GB

# Security and limits configuration
security:
  # Disable admin API for security
  admin_api_enabled: false

# Query timeout settings
query:
  max_samples: 50000000
  timeout: 2m
  lookback_delta: 5m

# Remote write/read endpoints (disabled for MVP)
remote_write: []
remote_read: []

# Exemplar storage settings
exemplar_storage:
  max_exemplars: 100000