openapi: 3.0.3
info:
  title: Arena MVP API
  version: 1.0.0
  description: REST API for Arena software evaluation platform
  contact:
    name: Arena Support
    email: support@arena.io

servers:
  - url: https://api.arena.io/v1
    description: Production API
  - url: https://staging-api.arena.io/v1
    description: Staging API

security:
  - bearerAuth: []

paths:
  /auth/magic-link:
    post:
      tags:
        - Authentication
      summary: Request magic link authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MagicLinkRequest'
      responses:
        '200':
          description: Magic link sent successfully
          headers:
            X-RateLimit-Limit:
              schema:
                type: integer
              description: Request limit per hour
        '400':
          description: Invalid email format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '429':
          description: Too many requests
          headers:
            Retry-After:
              schema:
                type: integer
              description: Seconds to wait before retrying

  /requests:
    post:
      tags:
        - Requests
      summary: Create software evaluation request
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRequest'
      responses:
        '201':
          description: Request created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Request'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Error:
      type: object
      properties:
        code:
          type: string
          description: Error code
          example: E1001
        message:
          type: string
          description: Error message
          example: Invalid credentials
        details:
          type: object
          description: Additional error details
      required:
        - code
        - message

    MagicLinkRequest:
      type: object
      properties:
        email:
          type: string
          format: email
          description: Business email address
          example: john@company.com
      required:
        - email

    CreateRequest:
      type: object
      properties:
        requirements:
          type: string
          description: Free-text requirements
          example: Looking for CRM software with email integration
        documents:
          type: array
          items:
            type: string
            format: binary
          description: Supporting documents
      required:
        - requirements

    Request:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Request identifier
        status:
          type: string
          enum:
            - draft
            - submitted
            - processing
            - completed
          description: Request status
        created_at:
          type: string
          format: date-time
          description: Creation timestamp
      required:
        - id
        - status
        - created_at

tags:
  - name: Authentication
    description: Authentication endpoints
  - name: Requests
    description: Software evaluation request management
  - name: Proposals
    description: Vendor proposal management
  - name: Vendors
    description: Vendor management and matching